closes #21

diff --git a/src/lxccu/source/patches/lxccu-2.9.12.patch b/src/lxccu/source/patches/lxccu-2.9.12.patch
--- a/src/lxccu/source/patches/lxccu-2.9.12.patch
+++ b/src/lxccu/source/patches/lxccu-2.9.12.patch
@@ -1,6 +1,6 @@
 diff -rupN fs_original/bin/mountSD fs/bin/mountSD
---- fs_original/bin/mountSD	2014-08-15 20:04:37.945874948 +0000
-+++ fs/bin/mountSD	2014-08-15 20:11:13.403783794 +0000
+--- fs_original/bin/mountSD	2014-10-11 02:16:42.830122862 +0200
++++ fs/bin/mountSD	2014-10-11 02:19:59.591554291 +0200
 @@ -1,10 +1,10 @@
  #!/bin/sh
  echo "Starte mountSD: $@" > /tmp/dudu
@@ -16,8 +16,8 @@ diff -rupN fs_original/bin/mountSD fs/bin/mountSD
 +# fi
  
 diff -rupN fs_original/bin/update_firmware_pre fs/bin/update_firmware_pre
---- fs_original/bin/update_firmware_pre	2014-08-15 20:04:38.089870169 +0000
-+++ fs/bin/update_firmware_pre	2014-08-15 20:11:13.407783252 +0000
+--- fs_original/bin/update_firmware_pre	2014-10-11 02:16:42.962118454 +0200
++++ fs/bin/update_firmware_pre	2014-10-11 02:20:06.975307864 +0200
 @@ -1,5 +1,5 @@
  #!/bin/sh
 -
@@ -114,8 +114,8 @@ diff -rupN fs_original/bin/update_firmware_pre fs/bin/update_firmware_pre
 +# pivot_root . oldroot
  
 diff -rupN fs_original/bin/update_firmware_run fs/bin/update_firmware_run
---- fs_original/bin/update_firmware_run	2014-08-15 20:04:38.089870169 +0000
-+++ fs/bin/update_firmware_run	2014-08-15 20:11:13.411782710 +0000
+--- fs_original/bin/update_firmware_run	2014-10-11 02:16:42.966118320 +0200
++++ fs/bin/update_firmware_run	2014-10-11 02:20:06.983307597 +0200
 @@ -1,36 +1,70 @@
  #!/bin/sh
  
@@ -219,14 +219,14 @@ diff -rupN fs_original/bin/update_firmware_run fs/bin/update_firmware_run
 +cd /var/
 +/var/update_script CCU2
 diff -rupN fs_original/etc/config_templates/ntpclient fs/etc/config_templates/ntpclient
---- fs_original/etc/config_templates/ntpclient	2014-08-15 20:04:39.429825699 +0000
-+++ fs/etc/config_templates/ntpclient	2014-08-15 20:11:13.415782168 +0000
+--- fs_original/etc/config_templates/ntpclient	2014-10-11 02:16:44.306073576 +0200
++++ fs/etc/config_templates/ntpclient	2014-10-11 02:20:06.991307330 +0200
 @@ -1 +1 @@
 -NTPSERVERS='ntp.homematic.com'
 +NTPSERVERS='0.de.pool.ntp.org'
 diff -rupN fs_original/etc/fstab fs/etc/fstab
---- fs_original/etc/fstab	2014-08-15 20:04:39.445825168 +0000
-+++ fs/etc/fstab	2014-08-15 20:11:13.419781626 +0000
+--- fs_original/etc/fstab	2014-10-11 02:16:44.318073175 +0200
++++ fs/etc/fstab	2014-10-11 02:20:06.995307197 +0200
 @@ -1,13 +1,3 @@
  # /etc/fstab: static file system information.
  #
@@ -241,9 +241,74 @@ diff -rupN fs_original/etc/fstab fs/etc/fstab
 -varfs           /var           tmpfs    defaults,size=196M 0      0
 -debugfs 	/sys/kernel/debug debugfs 		  0 	0
 -ubi1:user	/usr/local	ubifs	defaults,noatime,rw,sync	0 0
+diff -rupN fs_original/etc/init.d/_40UsbNetwork fs/etc/init.d/_40UsbNetwork
+--- fs_original/etc/init.d/_40UsbNetwork	1970-01-01 01:00:00.000000000 +0100
++++ fs/etc/init.d/_40UsbNetwork	2014-10-11 02:20:07.039305729 +0200
+@@ -0,0 +1,52 @@
++#!/bin/sh
++#
++# Starts Ethernet over USB
++#
++
++
++start() {
++	export TZ=`cat /etc/config/TZ`
++
++	echo -n "Starting network over usb: "
++		
++	if [ ! -f /etc/udhcpd.usb0.conf ]; then
++		echo "ERROR (file /etc/udhcp.usb0.conf not found)"
++	elif [ ! -f /etc/dnsd.conf ]; then
++		echo "ERROR (file /etc/dnsd.conf not found)"
++	else
++		ifconfig usb0 10.101.82.51 netmask 255.255.255.0
++		udhcpd -S /etc/udhcpd.usb0.conf
++		# disable DNS Server; CCU can only be access by ip address
++		#dnsd -d -c /etc/dnsd.conf -i 10.101.82.51
++		echo "OK"	
++	fi		
++}
++
++stop() {
++	echo -n "Stopping network over usb: "
++	killall udhcpd
++	killall dnsd	
++	echo "OK"
++}
++restart() {
++	stop
++	start
++}
++
++case "$1" in
++  start)
++	start
++	;;
++  stop)
++	stop
++	;;
++  restart|reload)
++	restart
++	;;
++  *)
++	echo "Usage: $0 {start|stop|restart}"
++	exit 1
++esac
++
++exit $?
++
+diff -rupN fs_original/etc/init.d/rcS fs/etc/init.d/rcS
+--- fs_original/etc/init.d/rcS	2014-10-11 02:16:44.226076247 +0200
++++ fs/etc/init.d/rcS	2014-10-11 02:20:07.043305595 +0200
+@@ -25,3 +25,4 @@ for i in /etc/init.d/S??* ;do
+     esac
+ done
+ 
++/bin/mountSD
+\ No newline at end of file
 diff -rupN fs_original/etc/init.d/S00eQ3SystemStart fs/etc/init.d/S00eQ3SystemStart
---- fs_original/etc/init.d/S00eQ3SystemStart	2014-08-15 20:04:39.377827424 +0000
-+++ fs/etc/init.d/S00eQ3SystemStart	2014-08-15 20:11:13.435779459 +0000
+--- fs_original/etc/init.d/S00eQ3SystemStart	2014-10-11 02:16:44.254075313 +0200
++++ fs/etc/init.d/S00eQ3SystemStart	2014-10-11 02:20:07.007306797 +0200
 @@ -4,104 +4,104 @@
  #
  
@@ -455,8 +520,8 @@ diff -rupN fs_original/etc/init.d/S00eQ3SystemStart fs/etc/init.d/S00eQ3SystemSt
  	exit 1
  esac
 diff -rupN fs_original/etc/init.d/S40UsbNetwork fs/etc/init.d/S40UsbNetwork
---- fs_original/etc/init.d/S40UsbNetwork	2014-08-15 20:04:39.373827557 +0000
-+++ fs/etc/init.d/S40UsbNetwork	1970-01-01 00:00:00.000000000 +0000
+--- fs_original/etc/init.d/S40UsbNetwork	2014-10-11 02:16:44.246075580 +0200
++++ fs/etc/init.d/S40UsbNetwork	1970-01-01 01:00:00.000000000 +0100
 @@ -1,52 +0,0 @@
 -#!/bin/sh
 -#
@@ -511,8 +576,8 @@ diff -rupN fs_original/etc/init.d/S40UsbNetwork fs/etc/init.d/S40UsbNetwork
 -exit $?
 -
 diff -rupN fs_original/etc/init.d/S50eq3configd fs/etc/init.d/S50eq3configd
---- fs_original/etc/init.d/S50eq3configd	2014-08-15 20:04:39.353828221 +0000
-+++ fs/etc/init.d/S50eq3configd	2014-08-15 20:11:13.447777834 +0000
+--- fs_original/etc/init.d/S50eq3configd	2014-10-11 02:16:44.226076247 +0200
++++ fs/etc/init.d/S50eq3configd	2014-10-11 02:20:07.019306396 +0200
 @@ -1,52 +1,52 @@
  #!/bin/sh
  #
@@ -595,8 +660,8 @@ diff -rupN fs_original/etc/init.d/S50eq3configd fs/etc/init.d/S50eq3configd
 +exit	$?
  
 diff -rupN fs_original/etc/init.d/S60rfd fs/etc/init.d/S60rfd
---- fs_original/etc/init.d/S60rfd	2014-08-15 20:04:39.385827159 +0000
-+++ fs/etc/init.d/S60rfd	2014-08-15 20:11:13.451777292 +0000
+--- fs_original/etc/init.d/S60rfd	2014-10-11 02:16:44.258075179 +0200
++++ fs/etc/init.d/S60rfd	2014-10-11 02:20:07.027306129 +0200
 @@ -57,8 +57,8 @@ init() {
  start() {
  	echo -n "Starting rfd: "
@@ -630,8 +695,8 @@ diff -rupN fs_original/etc/init.d/S60rfd fs/etc/init.d/S60rfd
  	exit 1
  esac
 diff -rupN fs_original/etc/init.d/S99eQ3SystemStarted fs/etc/init.d/S99eQ3SystemStarted
---- fs_original/etc/init.d/S99eQ3SystemStarted	2014-08-15 20:04:39.389827026 +0000
-+++ fs/etc/init.d/S99eQ3SystemStarted	2014-08-15 20:11:13.455776750 +0000
+--- fs_original/etc/init.d/S99eQ3SystemStarted	2014-10-11 02:16:44.262075045 +0200
++++ fs/etc/init.d/S99eQ3SystemStarted	2014-10-11 02:20:07.031305996 +0200
 @@ -4,32 +4,32 @@
  #
  
@@ -697,74 +762,9 @@ diff -rupN fs_original/etc/init.d/S99eQ3SystemStarted fs/etc/init.d/S99eQ3System
  	echo "Usage: $0 {start|stop|restart}"
  	exit 1
  esac
-diff -rupN fs_original/etc/init.d/_40UsbNetwork fs/etc/init.d/_40UsbNetwork
---- fs_original/etc/init.d/_40UsbNetwork	1970-01-01 00:00:00.000000000 +0000
-+++ fs/etc/init.d/_40UsbNetwork	2014-08-15 20:11:13.423781085 +0000
-@@ -0,0 +1,52 @@
-+#!/bin/sh
-+#
-+# Starts Ethernet over USB
-+#
-+
-+
-+start() {
-+	export TZ=`cat /etc/config/TZ`
-+
-+	echo -n "Starting network over usb: "
-+		
-+	if [ ! -f /etc/udhcpd.usb0.conf ]; then
-+		echo "ERROR (file /etc/udhcp.usb0.conf not found)"
-+	elif [ ! -f /etc/dnsd.conf ]; then
-+		echo "ERROR (file /etc/dnsd.conf not found)"
-+	else
-+		ifconfig usb0 10.101.82.51 netmask 255.255.255.0
-+		udhcpd -S /etc/udhcpd.usb0.conf
-+		# disable DNS Server; CCU can only be access by ip address
-+		#dnsd -d -c /etc/dnsd.conf -i 10.101.82.51
-+		echo "OK"	
-+	fi		
-+}
-+
-+stop() {
-+	echo -n "Stopping network over usb: "
-+	killall udhcpd
-+	killall dnsd	
-+	echo "OK"
-+}
-+restart() {
-+	stop
-+	start
-+}
-+
-+case "$1" in
-+  start)
-+	start
-+	;;
-+  stop)
-+	stop
-+	;;
-+  restart|reload)
-+	restart
-+	;;
-+  *)
-+	echo "Usage: $0 {start|stop|restart}"
-+	exit 1
-+esac
-+
-+exit $?
-+
-diff -rupN fs_original/etc/init.d/rcS fs/etc/init.d/rcS
---- fs_original/etc/init.d/rcS	2014-08-15 20:04:39.349828353 +0000
-+++ fs/etc/init.d/rcS	2014-08-15 20:11:13.431780001 +0000
-@@ -25,3 +25,4 @@ for i in /etc/init.d/S??* ;do
-     esac
- done
- 
-+/bin/mountSD
-\ No newline at end of file
 diff -rupN fs_original/etc/inittab fs/etc/inittab
---- fs_original/etc/inittab	2014-08-15 20:04:39.473824238 +0000
-+++ fs/etc/inittab	2014-08-15 20:11:13.459776208 +0000
+--- fs_original/etc/inittab	2014-10-11 02:16:44.346072241 +0200
++++ fs/etc/inittab	2014-10-11 02:20:07.051305328 +0200
 @@ -14,27 +14,31 @@
  # process   == program to run
  
@@ -804,8 +804,8 @@ diff -rupN fs_original/etc/inittab fs/etc/inittab
 +# create a console for lxc
 +tty1::respawn:/sbin/getty -L tty1 115200 linux
 diff -rupN fs_original/opt/mh/startup.sh fs/opt/mh/startup.sh
---- fs_original/opt/mh/startup.sh	2014-08-15 20:04:42.485724280 +0000
-+++ fs/opt/mh/startup.sh	2014-08-15 20:11:13.467775124 +0000
+--- fs_original/opt/mh/startup.sh	2014-10-11 02:16:47.353971800 +0200
++++ fs/opt/mh/startup.sh	2014-10-11 02:20:07.055305195 +0200
 @@ -19,9 +19,9 @@ if [ ! -e $USER_DIR ] ; then
  
  fi
@@ -820,8 +820,8 @@ diff -rupN fs_original/opt/mh/startup.sh fs/opt/mh/startup.sh
  
  l1=`ifconfig | grep 'eth0' | tr -s ' ' | cut -d ' ' -f5 | tr ':' '-'`
 diff -rupN fs_original/www/api/methods/bidcosrf/setconfiguration-rf.tcl fs/www/api/methods/bidcosrf/setconfiguration-rf.tcl
---- fs_original/www/api/methods/bidcosrf/setconfiguration-rf.tcl	2014-08-15 20:05:28.108210170 +0000
-+++ fs/www/api/methods/bidcosrf/setconfiguration-rf.tcl	2014-08-15 20:13:39.519125771 +0000
+--- fs_original/www/api/methods/bidcosrf/setconfiguration-rf.tcl	2014-10-11 02:17:26.260672697 +0200
++++ fs/www/api/methods/bidcosrf/setconfiguration-rf.tcl	2014-10-11 02:20:07.063304928 +0200
 @@ -39,13 +39,13 @@ puts $fd ""
  puts $fd ""	
  
@@ -844,8 +844,8 @@ diff -rupN fs_original/www/api/methods/bidcosrf/setconfiguration-rf.tcl fs/www/a
  #Lan Interfaces (RF)
  set i 1
 diff -rupN fs_original/www/config/control_panel.cgi fs/www/config/control_panel.cgi
---- fs_original/www/config/control_panel.cgi	2014-08-15 20:05:31.024113397 +0000
-+++ fs/www/config/control_panel.cgi	2014-08-15 20:11:13.479773499 +0000
+--- fs_original/www/config/control_panel.cgi	2014-10-11 02:17:29.384568395 +0200
++++ fs/www/config/control_panel.cgi	2014-10-11 02:20:07.067304794 +0200
 @@ -159,10 +159,12 @@ puts {
  
      <!-- Storage Settings -->
@@ -860,8 +860,8 @@ diff -rupN fs_original/www/config/control_panel.cgi fs/www/config/control_panel.
  
  	  </tr>
 diff -rupN fs_original/www/config/cp_maintenance.cgi fs/www/config/cp_maintenance.cgi
---- fs_original/www/config/cp_maintenance.cgi	2014-08-15 20:05:30.960115521 +0000
-+++ fs/www/config/cp_maintenance.cgi	2014-08-15 20:17:45.711925534 +0000
+--- fs_original/www/config/cp_maintenance.cgi	2014-10-11 02:17:29.312570799 +0200
++++ fs/www/config/cp_maintenance.cgi	2014-10-11 02:20:07.079304394 +0200
 @@ -341,92 +341,93 @@ proc action_put_page {} {
                  table_data {class="CLASS20904"} {width="400"} {
                      table {class="CLASS20909"} {
@@ -1035,8 +1035,38 @@ diff -rupN fs_original/www/config/cp_maintenance.cgi fs/www/config/cp_maintenanc
                  }
                  table_data {align="left"} {class="CLASS20921"} {
 diff -rupN fs_original/www/config/cp_security.cgi fs/www/config/cp_security.cgi
---- fs_original/www/config/cp_security.cgi	2014-08-15 20:05:31.012113795 +0000
-+++ fs/www/config/cp_security.cgi	2014-08-15 20:20:58.270728321 +0000
+--- fs_original/www/config/cp_security.cgi	2014-10-11 02:17:29.364569063 +0200
++++ fs/www/config/cp_security.cgi	2014-10-11 02:21:14.213064079 +0200
+@@ -474,12 +474,12 @@ proc action_backup_restore_go {} {
+     }
+ 		
+ 	if { "false" == $ccu1_backup } {	# backup for version >= 2
+-		exec umount /usr/local
+-        	exec /usr/sbin/ubidetach -p /dev/mtd6
+-        	exec /usr/sbin/ubiformat /dev/mtd6 -y
+-        	exec /usr/sbin/ubiattach -p /dev/mtd6
+-        	exec /usr/sbin/ubimkvol /dev/ubi1 -N user -m
+-        	exec mount /usr/local
++		# exec umount /usr/local
++        	# exec /usr/sbin/ubidetach -p /dev/mtd6
++        	# exec /usr/sbin/ubiformat /dev/mtd6 -y
++        	# exec /usr/sbin/ubiattach -p /dev/mtd6
++        	# exec /usr/sbin/ubimkvol /dev/ubi1 -N user -m
++        	# exec mount /usr/local
+ 
+ 		if { [catch {exec tar xzf /tmp/usr_local.tar.gz} errorMessage] } {
+ 			# set msg "Beim Einspielen des Systembackups ist ein Fehler aufgetreten. Bitte versuchen Sie es erneut. "
+@@ -566,8 +566,8 @@ proc action_backup_restore_go {} {
+ 	}
+ 	
+ 	if { "false" == $backuperror } {
+-        exec mount -o remount,ro /usr/local
+-        exec mount -o remount,rw /usr/local
++        # exec mount -o remount,ro /usr/local
++        # exec mount -o remount,rw /usr/local
+         division {class="popupTitle"} {
+             puts "\${dialogSettingsSecurityMessageSysBackupRestartSystemTitle}"
+         }
 @@ -808,38 +808,40 @@ proc action_put_page {} {
                      }
                  }
@@ -1111,8 +1141,8 @@ diff -rupN fs_original/www/config/cp_security.cgi fs/www/config/cp_security.cgi
              table_data {class="CLASS20807"} {
                puts "\${dialogSettingsSecurityTDSessionTimeout}"
 diff -rupN fs_original/www/config/cp_software.cgi fs/www/config/cp_software.cgi
---- fs_original/www/config/cp_software.cgi	2014-08-15 20:05:30.888117911 +0000
-+++ fs/www/config/cp_software.cgi	2014-08-15 20:22:05.833659984 +0000
+--- fs_original/www/config/cp_software.cgi	2014-10-11 02:17:29.236573336 +0200
++++ fs/www/config/cp_software.cgi	2014-10-11 02:20:07.099303726 +0200
 @@ -507,7 +507,9 @@ proc action_install_start {} {
      if {[isOldCCU]} {
          exec /sbin/init -q
